### ISSUE TITLE
backup and recovery credentials

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/talao-wallet#67]

**Comment by hawkbee1** [comment]
Globally 2 steps process: 
1/ The user wants to store in one or several safe place an encrypted file containing all his credentials.
2/ Later, the user wants to use this encrypted file to recover his credentials because he lost his phone or whatever...
 
Encryption: 
Encryption is done with a symetric key in order to be able to decrypt the file during recovery phase. 
Currently the application is generating asymetric keys to handle credentials. The child:
`final child = rootKey.derivePath("m/44'/60'/0'/0/0"); `
is the entry point to create our symetric key. We **may** use the package      https://pub.dev/packages/crypto_keys.
In this package documentation `print("Ciphertext: ${v.data}");` is probably the key we need to use for recovery.

Recovering the credentials : 
The user must provide the backup file and his recovery phrase (12 words mnemonic). Thanks to mnemonic the symetric key is recovered and file decryption can happen.

**Comment by hawkbee1** [comment]
We need to provide very clear recommendations to user when he is doing his  backup.

**Comment by hawkbee1** [comment]
optional idea 1: providing the user with a backup status : last backup was "backup date" and you added n credentials since then.
optional idea 2: Add backup status on credential list or detail.

**Comment by hawkbee1** [comment]
During the meeting yesterday I discovered we won't use the same mnemonic for the backup&recovery process (my misunderstanding). So, when the user ask for backup we create a mnemonic and display it. We don't store this new mnemonic in the wallet, we just use it to encrypt the file containing the credentials.

**Comment by hawkbee1** [comment]
And when user is doing recovery we will ask to enter the mnemonic used during backup, like we do when user launch the app for the fisrt time and enter an existing mnemonic.

**Comment by bibash28** [comment]
I got it  - every time we create backup we will use different 12phrases...

**Comment by hawkbee1** [comment]
After pressing upload backup file
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Deletion failed, path = '/var/mobile/Containers/Data/Application/985CDD00-F941-4379-A1EB-2CDA6F381E2E/Library/Caches' (OS Error: Operation not permitted, errno = 1)
#0      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:192:9)
#1      _rootRunUnary (dart:async/zone.dart:1434:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
<asynchronous suspension>
#3      _RecoveryCredentialPageState.build.<anonymous closure> (package:talao/drawer/recovery_credential/view/recovery_credential_page.dart:96:21)
<asynchronous suspension>
Application finished.

Same issue after uninstalling, recovering with first mnemonic, reseting wallet.

**Comment by hawkbee1** [comment]
failing on ios at this point because no files are present
    var appDir = (await getTemporaryDirectory()).path;
    await Directory(appDir).delete(recursive: true);

Later failing to decrypt because ext variable is used both with mnemonic and encrypted file. In following code I rename text into toto and it's working:
``` dart

 Future<void> recoverWallet(String text) async {
    emit(state.copyWith(status: RecoveryCredentialStatus.loading));
    //var appDir = (await getTemporaryDirectory()).path;
    //await Directory(appDir).delete(recursive: true);
    var result = await FilePicker.platform
        .pickFiles(type: FileType.custom, allowedExtensions: ['txt']);
    if (result != null) {
      try {
        var file = File(result.files.single.path!);
        var toto = await file.readAsString();
        //todo: verify text is json
        Map json = jsonDecode(toto);
        //todo: verify cipherText is available
        //todo: verify authenticationTag is available
        var encryption = Encryption(
            cipherText: json['cipherText'],
            authenticationTag: json['authenticationTag']);
        var decryptedText = await CryptoKeys().decrypt(text, encryption);
```

**Comment by bibash28** [comment]
I think we have to set following for android only,,
var appDir = (await getTemporaryDirectory()).path;
await Directory(appDir).delete(recursive: true);


P.S. dont forget to pull the latest before testing...
